use crate::config::OcfgConfig;
use handlebars::Handlebars;
use std::collections::HashMap;

pub struct TemplateEngine {
    handlebars: Handlebars<'static>,
}

impl TemplateEngine {
    pub fn new() -> Result<Self, crate::error::OcfgError> {
        let mut handlebars = Handlebars::new();
        
        // Register templates
        handlebars.register_template_string("setup_config_env", SETUP_CONFIG_ENV_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("setup_secrets_env", SETUP_SECRETS_ENV_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("nftables_hardening", NFTABLES_HARDENING_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("sysctl_hardening", SYSCTL_HARDENING_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("dnsmasq_config", DNSMASQ_CONFIG_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("firewall_config", FIREWALL_CONFIG_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        handlebars.register_template_string("openwrt_config", OPENWRT_CONFIG_TEMPLATE)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))?;
        
        Ok(Self { handlebars })
    }

    pub fn render_setup_config_env(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("setup_config_env", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_setup_secrets_env(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("setup_secrets_env", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_nftables_hardening(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("nftables_hardening", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_sysctl_hardening(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("sysctl_hardening", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_dnsmasq_config(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("dnsmasq_config", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_firewall_config(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("firewall_config", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }

    pub fn render_openwrt_config(&self, config: &OcfgConfig) -> Result<String, crate::error::OcfgError> {
        let mut data = HashMap::new();
        data.insert("config", config);
        
        self.handlebars.render("openwrt_config", &data)
            .map_err(|e| crate::error::OcfgError::Template(e.to_string()))
    }
}

impl Default for TemplateEngine {
    fn default() -> Self {
        Self::new().expect("Failed to create template engine")
    }
}

// Template definitions

const SETUP_CONFIG_ENV_TEMPLATE: &str = r#"#!/usr/bin/env bash
# setup-config.env — Configuration file generated by ocfg
# Source this file before running setup-build.sh to customize values

# ===========================================================================
# Network Interface Configuration
# ===========================================================================

export WAN_INTERFACE="${WAN_INTERFACE:-{{config.network.wan_interface}}}"
export LAN_INTERFACE="${LAN_INTERFACE:-{{config.network.lan_interface}}}"

# ===========================================================================
# DNS Configuration
# ===========================================================================

export DNS_DOH_UPSTREAM="${DNS_DOH_UPSTREAM:-{{config.dns.doh_upstream}}}"
export DNS_DOT_BOOTSTRAP="${DNS_DOT_BOOTSTRAP:-{{config.dns.dot_bootstrap}}}"
export DNS_PROXY_LISTEN_ADDR="${DNS_PROXY_LISTEN_ADDR:-{{config.dns.proxy_listen_addr}}}"
export DNS_PROXY_LISTEN_PORT="${DNS_PROXY_LISTEN_PORT:-{{config.dns.proxy_listen_port}}}"
export DNSSEC_ENABLED="${DNSSEC_ENABLED:-{{config.dns.dnssec_enabled}}}"

# ===========================================================================
# Wi-Fi Configuration
# ===========================================================================

export WIFI_24G_SSID="${WIFI_24G_SSID:-{{config.wifi.ssid_24g}}}"
export WIFI_5G_SSID="${WIFI_5G_SSID:-{{config.wifi.ssid_5g}}}"
export WIFI_COUNTRY="${WIFI_COUNTRY:-{{config.wifi.country}}}"
export WIFI_ISOLATE_GUEST="${WIFI_ISOLATE_GUEST:-{{config.wifi.isolate_guest}}}"
export WIFI_HIDDEN_SSID="${WIFI_HIDDEN_SSID:-{{config.wifi.hidden_ssid}}}"
export WIFI_MAX_ASSOC="${WIFI_MAX_ASSOC:-{{config.wifi.max_assoc}}}"

# ===========================================================================
# RADIUS Configuration
# ===========================================================================

export RADIUS_AUTH_PORT="${RADIUS_AUTH_PORT:-{{config.radius.auth_port}}}"
export RADIUS_ACCT_PORT="${RADIUS_ACCT_PORT:-{{config.radius.acct_port}}}"

# ===========================================================================
# Firewall & Security Configuration
# ===========================================================================

export SSH_IDLE_TIMEOUT="${SSH_IDLE_TIMEOUT:-{{config.ssh.idle_timeout}}}"
export SYN_FLOOD_RATE="${SYN_FLOOD_RATE:-{{config.firewall.syn_flood_rate}}}"
export CONN_FLOOD_RATE="${CONN_FLOOD_RATE:-{{config.firewall.conn_flood_rate}}}"
export ICMP_RATE_LIMIT="${ICMP_RATE_LIMIT:-{{config.firewall.icmp_rate_limit}}}"

# ===========================================================================
# VPN Configuration
# ===========================================================================

export WIREGUARD_PORT="${WIREGUARD_PORT:-{{config.vpn.wireguard_port}}}"
export OPENVPN_PORT="${OPENVPN_PORT:-{{config.vpn.openvpn_port}}}"

# ===========================================================================
# Build Configuration
# ===========================================================================

export BUILD_JOBS="${BUILD_JOBS:-{{config.build.jobs}}}"
export BUILD_VERBOSE="${BUILD_VERBOSE:-{{config.build.verbose}}}"

# ===========================================================================
# Feature Flags
# ===========================================================================

export ADBLOCK_ENABLED="${ADBLOCK_ENABLED:-{{config.features.adblock_enabled}}}"
export BANIP_ENABLED="${BANIP_ENABLED:-{{config.features.banip_enabled}}}"
export IPV6_ENABLED="${IPV6_ENABLED:-{{config.features.ipv6_enabled}}}"
"#;

const SETUP_SECRETS_ENV_TEMPLATE: &str = r#"#!/usr/bin/env bash
# setup-secrets.env — Sensitive authentication secrets generated by ocfg
# SECURITY WARNING: This file contains sensitive credentials.
# - Never commit this file to version control
# - Set file permissions to 600: chmod 600 setup-secrets.env

# ===========================================================================
# RADIUS Authentication Secrets
# ===========================================================================

{{#if config.secrets.radius_shared_secret}}
export RADIUS_SHARED_SECRET="${RADIUS_SHARED_SECRET:-{{config.secrets.radius_shared_secret}}}"
{{/if}}

{{#if config.secrets.radius_admin_password}}
export RADIUS_ADMIN_PASSWORD="${RADIUS_ADMIN_PASSWORD:-{{config.secrets.radius_admin_password}}}"
{{/if}}

# ===========================================================================
# Certificate & TLS Secrets
# ===========================================================================

{{#if config.secrets.ca_key_password}}
export CA_KEY_PASSWORD="${CA_KEY_PASSWORD:-{{config.secrets.ca_key_password}}}"
{{/if}}

{{#if config.secrets.server_key_password}}
export SERVER_KEY_PASSWORD="${SERVER_KEY_PASSWORD:-{{config.secrets.server_key_password}}}"
{{/if}}

export CERT_COUNTRY="${CERT_COUNTRY:-{{config.certificates.country}}}"
export CERT_STATE="${CERT_STATE:-{{config.certificates.state}}}"
export CERT_LOCALITY="${CERT_LOCALITY:-{{config.certificates.locality}}}"
export CERT_ORGANIZATION="${CERT_ORGANIZATION:-{{config.certificates.organization}}}"
export CERT_ORGANIZATIONAL_UNIT="${CERT_ORGANIZATIONAL_UNIT:-{{config.certificates.organizational_unit}}}"
export CERT_COMMON_NAME="${CERT_COMMON_NAME:-{{config.certificates.common_name}}}"
export CERT_EMAIL="${CERT_EMAIL:-{{config.certificates.email}}}"

# ===========================================================================
# SSH Authentication
# ===========================================================================

{{#if config.secrets.ssh_public_key}}
export SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY:-{{config.secrets.ssh_public_key}}}"
{{/if}}

# ===========================================================================
# Wi-Fi Enterprise Authentication
# ===========================================================================

{{#if config.secrets.wifi_radius_secret}}
export WIFI_RADIUS_SECRET="${WIFI_RADIUS_SECRET:-{{config.secrets.wifi_radius_secret}}}"
{{/if}}

{{#if config.secrets.wired_radius_secret}}
export WIRED_RADIUS_SECRET="${WIRED_RADIUS_SECRET:-{{config.secrets.wired_radius_secret}}}"
{{/if}}

{{#if config.secrets.wifi_24g_password}}
export WIFI_24G_PASSWORD="${WIFI_24G_PASSWORD:-{{config.secrets.wifi_24g_password}}}"
{{/if}}

{{#if config.secrets.wifi_5g_password}}
export WIFI_5G_PASSWORD="${WIFI_5G_PASSWORD:-{{config.secrets.wifi_5g_password}}}"
{{/if}}

# ===========================================================================
# Encryption Keys
# ===========================================================================

{{#if config.secrets.encryption_key}}
export ENCRYPTION_KEY="${ENCRYPTION_KEY:-{{config.secrets.encryption_key}}}"
{{/if}}

{{#if config.secrets.hmac_key}}
export HMAC_KEY="${HMAC_KEY:-{{config.secrets.hmac_key}}}"
{{/if}}
"#;

const NFTABLES_HARDENING_TEMPLATE: &str = r#"#!/usr/sbin/nft -f
# nftables hardening rules generated by ocfg
# This file should be placed at /etc/nftables.d/10-hardening.nft

table inet filter {
    chain raw_prerouting {
        type filter hook prerouting priority raw; policy accept;
        
        # Drop bogon packets
        ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 } iif {{config.network.wan_interface}} drop
        ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 } iif {{config.network.wan_interface}} drop
        
        # Drop IGMP and multicast
        ip protocol igmp drop
        ip daddr { 224.0.0.0/4, 255.255.255.255 } drop
        
        # Drop fragmented packets (optional, may break legitimate traffic)
        # ip frag-off != 0 drop
    }
    
    chain input {
        type filter hook input priority filter; policy drop;
        
        # Allow established and related connections
        ct state established,related accept
        
        # Drop invalid packets
        ct state invalid drop
        
        # Allow loopback
        iif lo accept
        
        # Allow ICMP with rate limiting
        {{#if config.security.enable_icmp_ratelimit}}
        ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded, parameter-problem } limit rate {{config.firewall.icmp_rate_limit}}/second accept
        {{/if}}
        
        # Drop port scans
        tcp flags & (fin|syn|rst|ack) == fin drop
        tcp flags & (fin|syn) == fin drop
        tcp flags & (fin|rst) == fin drop
        tcp flags & (syn|rst) == syn drop
        tcp flags & (fin|syn|rst|psh|ack|urg) == fin,syn,rst,psh,ack,urg drop
        tcp flags & (fin|syn|rst|psh|ack|urg) == 0 drop
    }
    
    chain forward {
        type filter hook forward priority filter; policy drop;
        
        # Allow established and related connections
        ct state established,related accept
        
        # Drop invalid packets
        ct state invalid drop
        
        # Drop multicast
        ip daddr { 224.0.0.0/4, 255.255.255.255 } drop
    }
}
"#;

const SYSCTL_HARDENING_TEMPLATE: &str = r#"# sysctl hardening configuration generated by ocfg
# This file should be placed at /etc/sysctl.d/20-hardening.conf

# Network hardening
{{#if config.security.enable_rp_filter}}
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
{{/if}}

{{#if config.security.enable_src_validation}}
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0
net.ipv6.conf.all.accept_source_route=0
net.ipv6.conf.default.accept_source_route=0
{{/if}}

# ICMP hardening
{{#if config.security.enable_icmp_ratelimit}}
net.ipv4.icmp_echo_ignore_all=1
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.icmp_ignore_bogus_error_responses=1
{{/if}}

# SYN cookies
{{#if config.security.enable_syn_cookies}}
net.ipv4.tcp_syncookies=1
{{/if}}

# TCP hardening
{{#if config.security.enable_tcp_timestamp_protection}}
net.ipv4.tcp_timestamps=0
{{/if}}

# Kernel hardening
{{#if config.security.enable_kaslr}}
kernel.kptr_restrict=2
{{/if}}

{{#if config.security.disable_core_dumps}}
kernel.core_pattern=/dev/null
fs.suid_dumpable=0
{{/if}}

# IGMP disabled
net.ipv4.igmp_max_memberships=0

# IPv6 disabled
{{#unless config.features.ipv6_enabled}}
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
{{/unless}}
"#;

const DNSMASQ_CONFIG_TEMPLATE: &str = r#"# dnsmasq configuration generated by ocfg
# This file should be placed at package/network/services/dnsmasq/files/dhcp.conf

# Disable DNSSEC
{{#if config.dns.dnssec_enabled}}
dnssec
dnssec-check-unsigned
trust-anchor=/,root.key
{{/if}}

# Forward all queries to dnsproxy
server=127.0.0.1#{{config.dns.proxy_listen_port}}
no-resolv

{{#unless config.features.ipv6_enabled}}
filter-aaaa
{{/unless}}

# DHCP configuration
dhcp-range=192.168.1.100,192.168.1.250,12h
dhcp-option=6,127.0.0.1
dhcp-option=3,192.168.1.1

# TFTP disabled
# enable-tftp
# tftp-root=/srv/tftp
"#;

const FIREWALL_CONFIG_TEMPLATE: &str = r#"# firewall configuration generated by ocfg
# This file should be placed at package/network/config/firewall/files/firewall.config

config defaults
    option syn_flood '1'
    option input 'DROP'
    option output 'ACCEPT'
    option forward 'DROP'

config zone
    option name 'lan'
    option input 'ACCEPT'
    option output 'ACCEPT'
    option forward 'ACCEPT'
    option network '{{config.network.lan_interface}}'

config zone
    option name 'wan'
    option input 'DROP'
    option output 'ACCEPT'
    option forward 'DROP'
    option network '{{config.network.wan_interface}}'
    option masq '1'
    option mtu_fix '1'

config forwarding
    option src 'lan'
    option dest 'wan'

config rule
    option name 'Allow-DHCP-Renew'
    option src 'wan'
    option proto 'udp'
    option dest_port '68'
    option target 'ACCEPT'
    option family 'ipv4'

config rule
    option name 'Allow-Ping'
    option src 'wan'
    option proto 'icmp'
    option icmp_type 'echo-request'
    option family 'ipv4'
    option limit '1000/sec'
    option target 'ACCEPT'

config rule
    option name 'Allow-IGMP'
    option src 'wan'
    option proto 'igmp'
    option family 'ipv4'
    option target 'ACCEPT'

config rule
    option name 'Allow-IPSec-ESP'
    option src 'wan'
    option dest 'lan'
    option proto 'esp'
    option target 'ACCEPT'

config rule
    option name 'Allow-ISAKMP'
    option src 'wan'
    option dest 'lan'
    option dest_port '500'
    option proto 'udp'
    option target 'ACCEPT'
"#;

const OPENWRT_CONFIG_TEMPLATE: &str = r#"#
# OpenWrt .config generated by ocfg
# Crypto library: {{config.build.crypto_library}}
#

# Target Platform
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_mt7622=y
CONFIG_TARGET_mediatek_mt7622_DEVICE_linksys_e8450-ubi=y

# Global build options
CONFIG_DEVEL=y
CONFIG_AUTOREMOVE=y

{{#if (eq config.build.crypto_library "openssl")}}
# -------------------------------------------------------
# Crypto: OpenSSL configuration
# -------------------------------------------------------
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libopenssl-legacy=y
CONFIG_PACKAGE_openssl-util=y

CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_EC2M=y
CONFIG_OPENSSL_WITH_DEPRECATED=y

# Disable mbedTLS and WolfSSL
# CONFIG_PACKAGE_libmbedtls is not set
# CONFIG_PACKAGE_mbedtls-util is not set
# CONFIG_PACKAGE_px5g-mbedtls is not set
# CONFIG_PACKAGE_libwolfssl is not set
# CONFIG_PACKAGE_wolfssl-util is not set
# CONFIG_PACKAGE_px5g-wolfssl is not set

# Package variants - OpenSSL only
CONFIG_PACKAGE_uencrypt-openssl=y
CONFIG_PACKAGE_micropython-openssl=y
CONFIG_PACKAGE_libzip-openssl=y
CONFIG_PACKAGE_libuhttpd-openssl=y
CONFIG_PACKAGE_libuwsc-openssl=y
CONFIG_PACKAGE_libwebsockets-openssl=y
CONFIG_PACKAGE_umurmur-openssl=y
CONFIG_PACKAGE_openvpn-openssl=y
CONFIG_PACKAGE_eapol-test-openssl=y
CONFIG_PACKAGE_wpa-supplicant-openssl=y
CONFIG_PACKAGE_hostapd-openssl=y
CONFIG_PACKAGE_wpad-openssl=y
CONFIG_PACKAGE_wpad-basic-openssl=y
CONFIG_PACKAGE_eapol-test-openssl=y

{{/if}}
{{#if (eq config.build.crypto_library "mbedtls")}}
# -------------------------------------------------------
# Crypto: MbedTLS configuration
# -------------------------------------------------------
CONFIG_PACKAGE_libmbedtls=y
CONFIG_PACKAGE_mbedtls-util=y
CONFIG_PACKAGE_px5g-mbedtls=y

# Disable OpenSSL and WolfSSL
# CONFIG_PACKAGE_libopenssl is not set
# CONFIG_PACKAGE_openssl-util is not set
# CONFIG_PACKAGE_libwolfssl is not set
# CONFIG_PACKAGE_wolfssl-util is not set

# Package variants - MbedTLS only
CONFIG_PACKAGE_uencrypt-mbedtls=y
CONFIG_PACKAGE_micropython-mbedtls=y
CONFIG_PACKAGE_libzip-mbedtls=y
CONFIG_PACKAGE_libuhttpd-mbedtls=y
CONFIG_PACKAGE_libuwsc-mbedtls=y
CONFIG_PACKAGE_libwebsockets-mbedtls=y
CONFIG_PACKAGE_umurmur-mbedtls=y
CONFIG_PACKAGE_openvpn-mbedtls=y
CONFIG_PACKAGE_eapol-test-mbedtls=y
CONFIG_PACKAGE_wpa-supplicant-mbedtls=y
CONFIG_PACKAGE_hostapd-mbedtls=y
CONFIG_PACKAGE_wpad-mbedtls=y
CONFIG_PACKAGE_wpad-basic-mbedtls=y
CONFIG_PACKAGE_eapol-test-mbedtls=y

{{/if}}
{{#if (eq config.build.crypto_library "wolfssl")}}
# -------------------------------------------------------
# Crypto: WolfSSL configuration
# -------------------------------------------------------
CONFIG_PACKAGE_libwolfssl=y
CONFIG_PACKAGE_wolfssl-util=y
CONFIG_PACKAGE_px5g-wolfssl=y

# Disable OpenSSL and MbedTLS
# CONFIG_PACKAGE_libopenssl is not set
# CONFIG_PACKAGE_openssl-util is not set
# CONFIG_PACKAGE_libmbedtls is not set
# CONFIG_PACKAGE_mbedtls-util is not set

# Package variants - WolfSSL only
CONFIG_PACKAGE_uencrypt-wolfssl=y
CONFIG_PACKAGE_micropython-wolfssl=y
CONFIG_PACKAGE_libzip-wolfssl=y
CONFIG_PACKAGE_libuhttpd-wolfssl=y
CONFIG_PACKAGE_libuwsc-wolfssl=y
CONFIG_PACKAGE_libwebsockets-wolfssl=y
CONFIG_PACKAGE_umurmur-wolfssl=y
CONFIG_PACKAGE_openvpn-wolfssl=y
CONFIG_PACKAGE_eapol-test-wolfssl=y
CONFIG_PACKAGE_wpa-supplicant-wolfssl=y
CONFIG_PACKAGE_hostapd-wolfssl=y
CONFIG_PACKAGE_wpad-wolfssl=y
CONFIG_PACKAGE_wpad-basic-wolfssl=y
CONFIG_PACKAGE_eapol-test-wolfssl=y

{{/if}}

# VPN support
{{#if config.features.vpn_enabled}}
CONFIG_PACKAGE_kmod-wireguard=y
CONFIG_PACKAGE_wireguard-tools=y
CONFIG_PACKAGE_kmod-tun=y
{{/if}}

# IPv6 configuration
{{#unless config.features.ipv6_enabled}}
CONFIG_IPV6=n
{{/if}}

# Kernel hardening options
{{#if config.security.enable_kaslr}}
CONFIG_RANDOMIZE_BASE=y
{{/if}}
{{#if config.security.enable_stack_protector}}
CONFIG_CC_STACKPROTECTOR=y
{{/if}}
{{#if config.security.enable_pti}}
CONFIG_PAGE_TABLE_ISOLATION=y
{{/if}}

# Multicast/IGMP
{{#unless config.features.ipv6_enabled}}
CONFIG_IP_MULTICAST=n
CONFIG_BRIDGE_IGMP_SNOOPING=n
{{/unless}}
"#;
